export const LOAD_PHONEBOOK_SUCCESS = 'LOAD_PHONEBOOK_SUCCESS'
export const LOAD_PHONEBOOK_FAILURE = 'LOAD_PHONEBOOK_FAILURE'

export const LOAD_MORE_PHONEBOOK_SUCCESS = 'LOAD_MORE_PHONEBOOK_SUCCESS'
export const LOAD_MORE_PHONEBOOK_FAILURE = 'LOAD_MORE_PHONEBOOK_FAILURE'

export const ADD_PHONEBOOK_SUCCESS = 'ADD_PHONEBOOK_SUCCESS'
export const ADD_PHONEBOOK_FAILURE = 'ADD_PHONEBOOK_FAILURE'

export const UPDATE_PHONEBOOK_SUCCESS = 'UPDATE_PHONEBOOK_SUCCESS'
export const UPDATE_PHONEBOOK_FAILURE = 'UPDATE_PHONEBOOK_FAILURE'

export const REMOVE_PHONEBOOK_SUCCESS = 'REMOVE_PHONEBOOK_SUCCESS'
export const REMOVE_PHONEBOOK_FAILURE = 'REMOVE_PHONEBOOK_FAILURE'